force-app/main/default/objects/Hierarchy_Configuration__mdt/Hierarchy_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Hierarchy Configuration</label>
    <pluralLabel>Hierarchy Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Hierarchy_Configuration__mdt/fields/Component_Object__c.field-meta.xml
<CustomField>
    <fullName>Component_Object__c</fullName>
    <description>API name of the object the hierarchy component will be displayed on.</description>
    <inlineHelpText>API name of the object the hierarchy component will be displayed on.</inlineHelpText>
    <label>Component Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HierarchyConfigurationsPicklist.cls
global with sharing class HierarchyConfigurationsPicklist extends VisualEditor.DynamicPickList {

	public List<Hierarchy_Configuration__mdt> allHierarchyConfigs;
	VisualEditor.DesignTimePageContext context;
	String naMessage = 'None Available';

	global HierarchyConfigurationsPicklist(VisualEditor.DesignTimePageContext context) {
		String queryStr = 'SELECT Id, Label FROM Hierarchy_Configuration__mdt';
		if (context.pageType == 'RecordPage') {
			queryStr += ' WHERE Component_Object__c = \'' + context.entityName + '\'';
			naMessage += ' for this Object';
		}
		this.allHierarchyConfigs = Database.query(queryStr);
		this.context = context;
	}
  
	global override VisualEditor.DataRow getDefaultValue() {
		VisualEditor.DataRow defaultValue;
		if (allHierarchyConfigs.size() > 0) {
			defaultValue = new VisualEditor.DataRow(
				(String) allHierarchyConfigs[0].get('Name'),
				(String) allHierarchyConfigs[0].get('Id')
			);
		} else {
			defaultValue = new VisualEditor.DataRow(naMessage, 'None');
		}
		return defaultValue;
	}

	global override VisualEditor.DynamicPickListRows getValues() {
	  VisualEditor.DynamicPickListRows myValues = new VisualEditor.DynamicPickListRows();
		if (allHierarchyConfigs.size() > 0) {
			for (Hierarchy_Configuration__mdt config : allHierarchyConfigs) {
				myValues.addRow(
					new VisualEditor.DataRow(
						String.valueOf(config.Label),
						String.valueOf(config.Id)
					)
				);
			}
		} else {
			myValues.addRow(new VisualEditor.DataRow(naMessage, 'None'));
		}
		return myValues;
	}
}